export default {
  products: [
    {
      _id: "1",
      name: "Slim shirt",
      brand: "Nike",
      category: "shirts",
      image: "/images/d1.jpeg",
      price: 22,
      rating: 4.5,
      numReviews: 213,
      countInStock: 5,
    },
    {
      _id: "2",
      name: "fit shirt",
      brand: "Tesla",
      category: "shirts",
      image: "/images/d1.jpeg",
      price: 44,
      rating: 50,
      numReviews: 23,
      countInStock: 3,
    },
    {
      _id: "3",
      name: "pants",
      brand: "BMW",
      category: "pants",
      image: "/images/d1.jpeg",
      price: 50,
      rating: 40,
      numReviews: 21,
      countInStock: 7,
    },
    {
      _id: "4",
      name: "pants",
      brand: "Toyota",
      category: "pants",
      image: "/images/d1.jpeg",
      price: 88,
      rating: 4,
      numReviews: 21,
      countInStock: 9,
    },
  ],
};
